version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
      target: prod
      args:
        node: dev
    env_file: .env
    image: akarpovi4/lst-nginx:1.0-dev
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main_network

  goapi:
    build:
      context: ./api
      target: prod
    env_file: .env
    image: akarpovi4/lst-goapi:1.0-dev
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "seccomp:unconfined"
    networks:
      - main_network

  redis:
    image: redis:6.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - 6379
    networks:
      - main_network

  postgres:
    image: postgres:14.1-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_network

volumes:
  pgdata:

networks:
  main_network: