version: "3.7"

services:
  go-api:
    build:
      context: ./sso/api
      target: debug
    environment:
      # go-api specific vars
      SECRET_KEY: ${SECRET_KEY}
      # database vars
      DATABASE_URI: "${MARIADB_SSO_USER}:${MARIADB_SSO_PASSWORD}@tcp(mariadb)/sso?parseTime=true"
      # smtp server vars
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    restart: always
    volumes:
      - ./sso/api/src:/usr/src
    depends_on:
      - mariadb
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "seccomp:unconfined"
    ports:
      - "5500:5500"
      - "2346:2346"
    networks:
      - main_network

  mariadb:
    image: mariadb:10.9
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    expose:
      - 3306
    ports:
      - '3307:3306'
    volumes:
      - mariadb_data:/var/lib/mysql  
      - ./mariadb_init.d:/docker-entrypoint-initdb.d   
    networks:
      - main_network

  microblog-api:
    build:
      context: ./microblog/api
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: "mysql+aiomysql://${MARIADB_MICROBLOG_USER}:${MARIADB_MICROBLOG_PASSWORD}@mariadb:3306/microblog?charset=utf8mb4"
    volumes:
      - ./microblog/api/src:/prj/src
      - ./microblog/api/tests:/prj/tests
      - ./microblog/api/alembic:/prj/alembic
    depends_on:
      - mariadb
    ports:
      - "8008:80"
    networks:
      - main_network

  elasticsearch:
    image: elasticsearch:8.6.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - 9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - main_network
  
  kibana:
    image: kibana:8.6.0
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
     - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - main_network

volumes:
  mariadb_data:
  elasticsearch-data:
  kibana-data:

networks:
  main_network: