version: "3.7"

services:
  go-api:
    build:
      context: ./sso/api
      target: debug
    environment:
      # go-api specific vars
      SECRET_KEY: ${SECRET_KEY}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      # database vars
      DATABASE_URL: "${MARIADB_SSO_USER}:${MARIADB_SSO_PASSWORD}@mariadb/sso?parseTime=true"
      # smtp server vars
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    restart: always
    volumes:
      - ./sso/api/src:/usr/src
    depends_on:
      - mariadb
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "seccomp:unconfined"
    ports:
      - "5500:5500"
      - "2346:2346"
    networks:
      - main_network

  mariadb:
    image: mariadb:10.9
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    expose:
      - 3306
    ports:
      - '3307:3306'
    volumes:
      - mariadb_data:/var/lib/mysql  
      - ./mariadb_init.d:/docker-entrypoint-initdb.d   
    networks:
      - main_network

  microblog-api:
    build:
      context: ./microblog/api
    restart: always
    environment:
      DATABASE_URL: "mysql+aiomysql://${MARIADB_MICROBLOG_USER}:${MARIADB_MICROBLOG_PASSWORD}@mariadb:3306/microblog?charset=utf8mb4"
    volumes:
      - ./microblog/api/app:/prj/app
      - ./microblog/api/alembic:/prj/alembic
    depends_on:
      - mariadb
    ports:
      - "8008:80"
    networks:
      - main_network

volumes:
  mariadb_data:

networks:
  main_network: