version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
      target: prod
      args:
        node: prod
    env_file: .env
    image: akarpovi4/lst-nginx:1.0
    volumes: 
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - goapi
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main_network

  goapi:
    build:
      context: ./api
      target: prod
    env_file: .env
    image: akarpovi4/lst-goapi:1.0
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "seccomp:unconfined"
    networks:
      - main_network

  redis:
    image: redis:6.2-alpine
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - 6379
    networks:
      - main_network

  postgres:
    image: postgres:14.1-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_network
  
  # gitlab:
  #   image: 'gitlab/gitlab-ee:latest'
  #   restart: always
  #   hostname: 'gitlab.akarpovich.online'
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'https://gitlab.akarpovich.online'
  #       # Add any other gitlab.rb configuration here, each on its own line
  #   volumes:
  #     - '$GITLAB_HOME/config:/etc/gitlab'
  #     - '$GITLAB_HOME/logs:/var/log/gitlab'
  #     - '$GITLAB_HOME/data:/var/opt/gitlab'
  #   shm_size: '256m'
  #   networks:
  #     - main_network
  

volumes:
  pgdata:

networks:
  main_network: