version: "3.7"

services:
  go-api:
    build:
      context: ./api
      target: debug
    env_file: .env
    restart: always
    volumes:
      - ./api/src:/usr/src
    depends_on:
      - mariadb
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "seccomp:unconfined"
    ports:
      - "5500:5500"
      - "2346:2346"
    networks:
      - main_network

  mariadb:
    image: mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    expose:
      - 3306
    ports:
      - '3307:3306'
    volumes:
      - mariadb_data:/var/lib/mysql    
    networks:
      - main_network

volumes:
  mariadb_data:

networks:
  main_network: